### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by xxbing** [SoliaRdi/sell-angler-tokens#4]
[05:29:08.233] [proxy] Client disconnected
[05:35:25.887] [proxy] Client connected (TW v79.7)
[05:35:58.515] [mods] ERROR: Unable to load module information for "sell-angler-tokens-master"
[05:35:58.519] SyntaxError: Unexpected token } in JSON at position 200
    at JSON.parse (<anonymous>)
    at loadModuleInfo (E:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleInstallation.js:142:39)
    at listModules.forEach.name (E:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:73:30)
    at Array.forEach (<anonymous>)
    at ModuleManager.loadAll (E:\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:69:38)
    at ConnectionManager.start (E:\CaaliTeraProxy\bin\connectionManager.js:52:43)
    at Server.net.createServer.socket (E:\CaaliTeraProxy\bin\proxy.js:134:74)
    at Server.emit (events.js:182:13)
    at TCP.onconnection (net.js:1519:8)

**Comment by Moriang27** [comment]
SyntaxError: Unexpected token """""""'""}"""""""" in JSON at position 200


to fix!
