### ISSUE TITLE
error could not be loaded

### ISSUE THREAD

**Issue by kpinddd** [SoliaRdi/sell-angler-tokens#5]
Error: [dispatch] hook: unmapped packet "S_MEDAL_STORE_BASKET"
    at Dispatch.createHook (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at new SellAnglerTokens (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\mods\sell-angler-tokens-master\index.js:75:6)
    at ModuleManager.load (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:157:35)
    at installedModules.forEach.mod (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (C:\Users\kpind\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:182:13)

**Comment by SoliaRdi** [comment]
And? You have to map this opcodes yourself, if they not here. "Repo will contains opcodes only for RU"

**Comment by kpinddd** [comment]
how i can do it
